/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Head: typeof import('./src/components/Head.vue')['default']
    HeadBar: typeof import('./src/components/HeadBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAlarmFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconAlarmFill']
    IconAppOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconAppOutline']
    IconEmailFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconEmailFill']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YkAvatar: typeof import('@yike-design/ui')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui')['YkBadge']
    YkButton: typeof import('@yike-design/ui')['YkButton']
    YkHeadbar: typeof import('@yike-design/ui')['YkHeadbar']
    YkSpace: typeof import('@yike-design/ui')['YkSpace']
    YkText: typeof import('@yike-design/ui')['YkText']
    YkTheme: typeof import('@yike-design/ui')['YkTheme']
  }
}
