/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/overview/Card.vue')['default']
    Cicle: typeof import('./src/components/Echarts/Cicle.vue')['default']
    Circle: typeof import('./src/components/Echarts/Circle.vue')['default']
    CommentItem: typeof import('./src/components/langue/CommentItem.vue')['default']
    Comments: typeof import('./src/components/langue/Comments.vue')['default']
    copy: typeof import('./src/components/Echarts/Line copy.vue')['default']
    DatasEcharts: typeof import('./src/components/overview/DatasEcharts.vue')['default']
    Head: typeof import('./src/components/Head.vue')['default']
    HeadBar: typeof import('./src/components/HeadBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAlarmFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconAlarmFill']
    IconAppOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconAppOutline']
    IconDeleteOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconDeleteOutline']
    IconEmailFill: typeof import('@yike-design/ui/es/components/svg-icon')['IconEmailFill']
    IconPlusOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconPlusOutline']
    IconSearchOutline: typeof import('@yike-design/ui/es/components/svg-icon')['IconSearchOutline']
    Line: typeof import('./src/components/Echarts/Line.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    PrivateMessage: typeof import('./src/components/langue/PrivateMessage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopTitleBar: typeof import('./src/components/TopTitleBar.vue')['default']
    YkAvatar: typeof import('@yike-design/ui')['YkAvatar']
    YkBadge: typeof import('@yike-design/ui')['YkBadge']
    YkButton: typeof import('@yike-design/ui')['YkButton']
    YkHeadbar: typeof import('@yike-design/ui')['YkHeadbar']
    YkInputSearch: typeof import('@yike-design/ui')['YkInputSearch']
    YkPagination: typeof import('@yike-design/ui')['YkPagination']
    YkRadio: typeof import('@yike-design/ui')['YkRadio']
    YkRadioGroup: typeof import('@yike-design/ui')['YkRadioGroup']
    YkSc: typeof import('@yike-design/ui')['YkSc']
    YkScr: typeof import('@yike-design/ui')['YkScr']
    YkScrollbar: typeof import('@yike-design/ui')['YkScrollbar']
    YkSpace: typeof import('@yike-design/ui')['YkSpace']
    YkTag: typeof import('@yike-design/ui')['YkTag']
    YkText: typeof import('@yike-design/ui')['YkText']
    YkTheme: typeof import('@yike-design/ui')['YkTheme']
    YkTitle: typeof import('@yike-design/ui')['YkTitle']
  }
}
